/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mybaby.android_final_project.EasyUtils.ezgrowth;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int stethascope=0x7f020001;
    }
    public static final class id {
        public static final int AgeLbl=0x7f050001;
        public static final int AgeText=0x7f050002;
        public static final int FemaleRadioButton=0x7f050011;
        public static final int HeadSizeInfo=0x7f05000e;
        public static final int HeadSizeLbl=0x7f05000c;
        public static final int HeadSizeText=0x7f05000d;
        public static final int LengthInfo=0x7f05000b;
        public static final int LengthLbl=0x7f050009;
        public static final int LengthText=0x7f05000a;
        public static final int MaleRadioButton=0x7f050010;
        public static final int RadioGroupMaleFemale=0x7f05000f;
        public static final int ResultsBtn=0x7f050012;
        public static final int ResultsLbl=0x7f050013;
        public static final int StatureInfo=0x7f050008;
        public static final int StatureLbl=0x7f050006;
        public static final int StatureText=0x7f050007;
        public static final int TitleLbl=0x7f050000;
        public static final int WeightInfo=0x7f050005;
        public static final int WeightLbl=0x7f050003;
        public static final int WeightText=0x7f050004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
